### ISSUE TITLE
[PE-D] Undefined behaviour when adding a duplicate policy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#256] opened 2021-10-30 09:11 UTC
Steps to reproduce:
1. View a client.
2. Add a valid policy.
3. Add the same policy again.

Expected behaviour: Either add the policy to the list, or display an error message warning about a duplicate policy.

Actual behaviour: Policy added message displayed, but no new policy appears.

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/803d5f62-90f5-4a40-86bf-1568d0afc619.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LMAOboxhack/ped#11

**Comment by bharathcs** [comment] 2021-10-30 09:19
Duplicate of #206

**Closed by bharathcs** 2021-10-30 09:19 UTC
