### ISSUE TITLE
[PE-D] Removing policies is buggy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#243] opened 2021-10-30 06:49 UTC
![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/fb3ff1ec-01dd-44e7-8cba-bae52707780c.png)

End result (first policy not removed): 

![image.png](https://raw.githubusercontent.com/BenjaminLHR/ped/main/files/fd101dce-b277-4eba-8d31-8d691686aff5.png)

Similar issue as removing of asset

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: BenjaminLHR/ped#7

**Comment by bharathcs** [comment] 2021-10-30 08:01
Duplicate of #217

**Closed by bharathcs** 2021-10-30 08:01 UTC
