### ISSUE TITLE
[PE-D] Undefined behaviour when adding a duplicate asset

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#262] opened 2021-10-30 09:59 UTC
Steps to reproduce:

1. View a client.
2. Add a valid asset.
3. Attempt to add the same asset again.

Expected behaviour: Either add the asset to the list, or display an error message warning about a duplicate asset.

Actual behaviour: Asset added message displayed, but no new asset appears.

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/adc38071-b681-4f2b-a247-defe1ecbf7ad.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LMAOboxhack/ped#15

**Comment by bharathcs** [comment] 2021-10-30 12:30
Duplicate of #207

**Closed by bharathcs** 2021-10-30 12:30 UTC

**Comment by bharathcs** [comment] 2021-10-30 12:32
Duplicate of #207

**Comment by bharathcs** [comment] 2021-10-30 12:33
Duplicate of #206
