### ISSUE TITLE
[PE-D] Append command message unclear about type of policy/asset/liability added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#245] opened 2021-10-30 07:21 UTC
Steps to reproduce:

1. View a client.
2. Add a policy/asset/liability.

Expected: Message indicates which of policy/asset/liabilities were added.

Actual: Message is unclear about which is added.

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/0c1f5950-3d69-45c1-b7a3-9423836d22b0.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: LMAOboxhack/ped#8

**Comment by bharathcs** [comment] 2021-10-30 07:35
Duplicate of #231

**Closed by bharathcs** 2021-10-30 07:35 UTC
