### ISSUE TITLE
[PE-D] No warning window when using the clear command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#276] opened 2021-10-30 11:42 UTC
I do feel like it is a bit too easy to clear the list, and there are chances where the user accidentally clears out the address book. Suggestion: It could be better if you can include some kind of warning window to prompt the user to confirm that the entire list will be cleared.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HalphasX/ped#3

**Comment by bharathcs** [comment] 2021-10-30 12:35
Duplicate of #263

**Closed by bharathcs** 2021-10-30 12:35 UTC
