### ISSUE TITLE
[PE-D] Tag issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#283] opened 2021-10-30 11:55 UTC
I understand that there are no commands specific to tags, but I think it is better to just remove tag as a whole. The tags can not be edited, found, sorted, and listed in any way. There is no functionality to search based on tags as well, so I don't see what tags do other than as a cosmetic.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HalphasX/ped#10

**Comment by bharathcs** [comment] 2021-10-30 12:23
Duplicate of #160

**Closed by bharathcs** 2021-10-30 12:23 UTC
