### ISSUE TITLE
[PE-D] Adding of liabilities with invalid fields displays incorrect error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#291] opened 2021-10-31 07:50 UTC
Steps to reproduce:

1. View a client
2. Add a liability with missing fields

Expected: Error message about missing fields.

Actual: Error message about empty spaces and new lines.

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/6f136711-fd41-44e1-93f7-ae21e0c2d82c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LMAOboxhack/ped#7

**Comment by bharathcs** [comment] 2021-11-01 02:32
Duplicate of #231

**Closed by bharathcs** 2021-11-01 02:32 UTC
