### ISSUE TITLE
[PE-D] Command summary gives incorrect example for 'append policy'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#252] opened 2021-10-30 08:14 UTC
Steps to reproduce: Go to the command summary section of the UG.

Expected: Correct example command for 'append policy' given.

Actual: Example command for 'append asset' given instead. 

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/3496cf03-fda0-445c-8129-a185dc0353f4.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: LMAOboxhack/ped#9

**Comment by bharathcs** [comment] 2021-10-30 08:27
Duplicate of #231

**Closed by bharathcs** 2021-10-30 08:27 UTC
