### ISSUE TITLE
[PE-D] Adding of asset with invalid fields displays incorrect error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W16-1/tp#258] opened 2021-10-30 09:27 UTC
Steps to reproduce:

1. View a client
2. Add an asset with incorrect fields

Expected: Error message showing the correct command format.

Actual: Error message about empty spaces and new lines.

![image.png](https://raw.githubusercontent.com/LMAOboxhack/ped/main/files/80174e09-3e81-442a-9491-567c5415987a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: LMAOboxhack/ped#12

**Comment by bharathcs** [comment] 2021-10-30 09:28
Duplicate of #231

**Closed by bharathcs** 2021-10-30 09:28 UTC
